### ISSUE TITLE
Can’t get BLID or Password

### ISSUE THREAD

**Issue by natesor** [karlvr/homebridge-roomba2#103]
<I have read all the guides, tried a mim attack using Charles and I am in over my head. Not sure why but I keep getting errors when I try to run any blid or password request>

Versions

HOOBS: 4.1.22
Node: 16.14.0
Plugin: 1.6.0
Terminal Output Below:

hoobs@hoobs:~$ sudo hbs bridge list
sudo: unable to resolve host hoobs: No address associated with hostname

id | type | display | port | pin | username | advertiser

hub | hub | Hub | 80 | [031-45-154](tel:031-45-154) | 08:3A:F0:99:32:23 |
hoobs | bridge | HOOBS | 51826 | [031-45-154](tel:031-45-154) | AA:39:31:33:9F:2C | bonjour

hoobs@hoobs:$ cd /var/lib/hoobs/BRIDGE-ID/node_modules/dorita980
-bash: cd: /var/lib/hoobs/BRIDGE-ID/node_modules/dorita980: No such file or directory
hoobs@hoobs:$ cd /var/lib/hoobs/hoobs/node_modules/dorita980
hoobs@hoobs:/var/lib/hoobs/hoobs/node_modules/dorita980$ sudo npm install && node ./bin/getpassword.js 10.0.0.51
sudo: unable to resolve host hoobs: No address associated with hostname

up to date, audited 355 packages in 5s

6 packages are looking for funding
run npm fund for details

21 vulnerabilities (1 low, 13 moderate, 5 high, 2 critical)

To address issues that do not require attention, run:
npm audit fix

To address all issues (including breaking changes), run:
npm audit fix --force

Run npm audit for details.
Make sure your robot is on the Home Base and powered on (green lights on). Then press and hold the HOME button (or DOCK+SPOT on some models) on your robot until it plays a series of tones (about 2 seconds). Release the button and your robot will flash WIFI light.
Then press any key here...
Robot Data:
undefined
node:events:498
throw er; // Unhandled 'error' event
^

Error: connect EHOSTUNREACH 10.0.0.51:8883
at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16)
Emitted 'error' event on TLSSocket instance at:
at emitErrorNT (node:internal/streams/destroy:157:8)
at emitErrorCloseNT (node:internal/streams/destroy:122:3)
at processTicksAndRejections (node:internal/process/task_queues:83:21) {
errno: -113,
code: 'EHOSTUNREACH',
syscall: 'connect',
address: '10.0.0.51',
port: 8883
}
hoobs@hoobs:/var/lib/hoobs/hoobs/node_modules/dorita980$

**Comment by karlvr** [comment]
@natesor 1) are you sure that's the correct IP address for your Roomba? How did you obtain it?

2) is `hoobs` on the same network as it? What's `hoobs`'s IP address

3) can you ping that IP address?

**Comment by vfontes** [comment]
I had this issue in the past with a Roomba i7. If you hold HOME and SPOT, the robot will be disconnected from the network, hence the `EHOSTUNREACH ` error.

You need to hold HOME for about 2 seconds, then `getpassword.js` should be able to connect and obtain the password.

**Comment by karlvr** [comment]
@natesor if you have tried again, please report back. In the meantime I'm closing this support issue.
