### ISSUE TITLE
Repeated and constant releasing of unexpected Roomba instances

### ISSUE THREAD

**Issue by jdgorelick** [karlvr/homebridge-roomba2#108]
### Current Behavior
Lots of unexpected roomba instances clogging logs. Continues occurring for both of my Roombas and my Braava

### Versions
- **Homebridge**: 1.4.0
- **Node**:       16.14.0
- **Plugin**:       1.3.1

### Homebridge Log / Command Output
```
[15/03/2022, 11:28:00] [Braava Jet m6] Releasing an unexpected Roomba instance
[15/03/2022, 11:29:01] [Braava Jet m6] Releasing an unexpected Roomba instance
[15/03/2022, 11:30:02] [Braava Jet m6] Releasing an unexpected Roomba instance
[15/03/2022, 11:31:04] [Braava Jet m6] Releasing an unexpected Roomba instance
[15/03/2022, 11:32:06] [Braava Jet m6] Releasing an unexpected Roomba instance
[15/03/2022, 11:32:49] [Roomba i7+] Releasing an unexpected Roomba instance
[15/03/2022, 11:33:08] [Braava Jet m6] Releasing an unexpected Roomba instance
```

**Comment by floriangrotz** [comment]
Same issue here, but only on Roomba m6

**Comment by Bitweidi** [comment]
Same issue on 3 Devices (m6, i7, 980)

**Comment by brsexton** [comment]
I'm having the same issue as well. I have also noticed that the green light on the Roomba turns off for a few seconds and then back on around the time this error occurs.

**Comment by maverick85** [comment]
> Same here on my 960. It worked flawlessly before. Now it won't start on first turn on. Have to do it twice. These are the logs:
> 
> ```
> [5/23/2022, 11:06:08 AM] [Roomba 960] Starting Roomba
> [5/23/2022, 11:06:17 AM] [Roomba 960] Starting Roomba
> [5/23/2022, 11:06:20 AM] [Roomba 960] Releasing an unexpected Roomba instance
> [5/23/2022, 11:06:23 AM] [Roomba 960] Releasing an unexpected Roomba instance
> [5/23/2022, 11:06:27 AM] [Roomba 960] Releasing an unexpected Roomba instance
> [5/23/2022, 11:06:31 AM] [Roomba 960] Releasing an unexpected Roomba instance
> [5/23/2022, 11:06:33 AM] [Roomba 960] Stopping Roomba
> [5/23/2022, 11:06:38 AM] [Roomba 960] Starting Roomba
> [5/23/2022, 11:06:42 AM] [Roomba 960] Stopping Roomba
> ```

I’m sorry but how do you do that start stop? Thank you

**Comment by arminf82** [comment]
Same here with Braava M6.

**Comment by maverick85** [comment]
@arminf82 please take a look here: https://github.com/karlvr/homebridge-roomba2/issues/119

both for a possible fix and honestly homebridge is history home-assistant is much better, robust and compatible.

**Comment by karlvr** [comment]
@jdgorelick do you have anything else trying to connect to your Roomba(s)? Connection Timeouts generally mean either the IP is wrong, or something else is holding the connection to your Roomba.

**Comment by karlvr** [comment]
I am currently working to reduce the amount of logging from the plug-in. Tracked under #113
