### ISSUE TITLE
HomeKit app won’t see my J7

### ISSUE THREAD

**Issue by ottoman42** [karlvr/homebridge-roomba2#116]
Hi I have given the plug-in my robot’s serial number it’s Password blid, name and IP address but I’m still getting a no response error and the log is saying there are a ton of time outs for the robot. (See attached images.) anyone know what’s going on? 

Thanks!
-
![774DE0A9-4BFE-4897-8D01-B988983C08DC](https://user-images.githubusercontent.com/18506925/168700793-0477026b-25d4-4824-b7f4-b1261cd7e80f.jpeg)
![E6E2A0E2-D345-474D-BB8D-AD77F419CB0C](https://user-images.githubusercontent.com/18506925/168700794-1878428f-b6ee-4acc-8057-e0e72455eafd.jpeg)

**Comment by ottoman42** [comment]
Looks like it’s the same issue as #106

**Comment by kkissane0328** [comment]
Seeing the same exact issue with mine as well. 980 works fine but J7 is a no go .Same exact errors

**Comment by longman391** [comment]
+1 here as well. It doesn't appear this is working at all with the J7.

**Comment by ottoman42** [comment]
Yeah I deleted the plugin and gave up.
