### ISSUE TITLE
cannot get any credential with given script

### ISSUE THREAD

**Issue by Ddjay** [karlvr/homebridge-roomba2#118]
in Setup section, it mentioned : 

"2. Open a terminal on your Homebridge system, either using ssh or by using the Homebridge Terminal located in the ⋮ menu, top-right in the Homebridge UI."
-> it is mentioned on top of Homebridge Terminal : `Note: This is a restricted shell, sudo and npm cannot be used here`

Next, 
"3. Change into the directory where the plugin is installed: cd $(npm root -g)/homebridge-roomba2"
-> my Terminal says : `-bash: cd: /usr/local/lib/node_modules/homebridge-roomba2: No such file or directory`

Next,
"4. Type `sudo npm run getrobotpwd <IP ADDRESS>` (replacing <IP ADDRESS> with the IP address you discovered above)."
-> wherever I enter this command, I still have tons of errors about files location.
I tried to run this command in each folder or folder alias I've found in the system in /var/lib/homebridge such as
```
/var/lib/homebridge/node_modules/.pnpm/homebridge-roomba2@1.3.1/node_modules/homebridge-roomba2
/var/lib/homebridge/node_modules/homebridge-roomba2
```
```
sh: 1: cd: can't cd to node_modules/dorita980
npm ERR! code 2
npm ERR! path /var/lib/homebridge/node_modules/.pnpm/homebridge-roomba2@1.3.1/node_modules/homebridge-roomba2
npm ERR! command failed
npm ERR! command sh -c cd node_modules/dorita980 && npm install && node ./bin/getpassword.js "192.168.1.41"
```
```
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /var/lib/homebridge/node_modules/.pnpm/homebridge-roomba2@1.3.1/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/var/lib/homebridge/node_modules/.pnpm/homebridge-roomba2@1.3.1/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 
```
```
sh: 1: cd: can't cd to node_modules/dorita980
npm ERR! code 2
npm ERR! path /var/lib/homebridge/node_modules/.pnpm/homebridge-roomba2@1.3.1/node_modules/homebridge-roomba2
npm ERR! command failed
npm ERR! command sh -c cd node_modules/dorita980 && npm install && node ./bin/getpassword.js "192.168.1.41"
```

I am using Raspberry Pi OS up to date of course.

OMG that's not very simple! I spent couple hours on that.
Nowhere it is explained that I had to install `npm` btw

I f anyone could help to fix my problem, it would be very appreciated.

**Comment by Cyrille556** [comment]
Hello, I have exactly the same problem, did you find the solution? THANKS
