### ISSUE TITLE
Braava Jet M6 reporting error continuously 

### ISSUE THREAD

**Issue by redeemer666** [karlvr/homebridge-roomba2#120]
I have 2 instances of this plugin, one for an S9+ (it work’s flawlessly) and the other one for a Braava Jet M6.

This second one report every 10-15 seconds the error attached. Plugin itself works fine, but I don’t know why this happens.

If you need something else, please let me know.

Thank you!
![Error](https://user-images.githubusercontent.com/9434736/171591181-8d013986-f830-4dac-9bbc-bbfec1fb3c41.png)

**Comment by Smexhy** [comment]
Same for 980

**Comment by dr** [comment]
Homebridge logs don't throw an error but HomeKit shows the Braava jet m6 as offline.  My Roomba s9 has no issues and works perfectly with this plugin.

**Comment by javiusmaximus** [comment]
Had the same issue with an i7. I was getting the same errors and was able to get it working after setting a static IP to the Roomba. Seems like the error started because the IP changed. Try setting a static IP to the Roomba and check that the IP you assign is the same in the plugin settings.

**Comment by Smexhy** [comment]
> Had the same issue with an i7. I was getting the same errors and was able to get it working after setting a static IP to the Roomba. Seems like the error started because the IP changed. Try setting a static IP to the Roomba and check that the IP you assign is the same in the plugin settings.

I have static IP and same as in the config though error is still happening.

**Comment by redeemer666** [comment]
Static IP on both my Roomba and Braava already set up, but still it shows the issue. As I say, this happens only on the Braava, not the Roomba s9+

**Comment by Skyman81** [comment]
problem with nodes...
downgrade it:
sudo hb-service update-node 16.18.1

**Comment by karlvr** [comment]
Please re-open if this problem persists and is not related to the node version issue.
