### ISSUE TITLE
Feature Request: Roomba Switch configurable to Stateful

### ISSUE THREAD

**Issue by whreams** [karlvr/homebridge-roomba2#21]
### Expected Behavior
Upon choosing the Roomba accessory, do not use the slider/switch, but allow for the user to configure the switch to be stateful - like a simple toggle button.

### Current Behavior
Current accessory is configured as a switch and requires the user to use a slider to turn on/off the Roomba. 

### Steps to Reproduce (for bugs)
N/A

### Versions

- **Homebridge**: 1.1.6
- **Node**:       12.16.3
- **Plugin**:      1.2.0

**Comment by iRayanKhan** [comment]
The whole point of it being a switch, is so that you can see if it's on, or not. 

You can just tap on the switch to control it, you don't have to slide on it.

You can feel free to open a PR, and configure it to be a button.
