### ISSUE TITLE
roomba 965 wifi outage changes local ip address

### ISSUE THREAD

**Issue by moiko2416** [karlvr/homebridge-roomba2#30]
### Expected Behavior
roomba 965 connected to HB via this plugin
when wifi is reset or has power outage , ip address of roomba should stay

### Current Behavior
when wifi is reset or by power outage, roomba ip address is changed. then plugin settings must  be changed and roomba restarted 

### Versions

- **Homebridge**: `homebridge 1.2.5`
- **Node**:       `node --version`
- **Plugin**:         

### Configuration

```json

```

### Homebridge Log / Command Output

```

```

**Comment by Pblondin123** [comment]
i made roomba a static IP on my router, actually any HB device which i include in my config i make the device static IP before

**Comment by karlvr** [comment]
@moiko2416 this is not an issue with this plugin. You will need to setup a static IP for your Roomba on your DHCP server.
