### ISSUE TITLE
the lights on my roomba 896 stay on

### ISSUE THREAD

**Issue by Cyrille556** [karlvr/homebridge-roomba2#32]
Hello, I just integrated my roomba 896 into homebridge, it works great!
  I just have a small problem, the robot lights are constantly on since integration with homebridge.

**Comment by Write** [comment]
Hi someone had this issue, go [here](https://github.com/iRayanKhan/homebridge-roomba2/issues/18) to see his solution

**Comment by karlvr** [comment]
@Cyrille556 I hope the above helper with your problem. If not I'd be interested to hear your results with the latest beta version of the plugin.
