### ISSUE TITLE
when local wifi restarted , roomba changes the IP address 

### ISSUE THREAD

**Issue by moiko2416** [karlvr/homebridge-roomba2#36]
hi guys

i am using this code to connect my roomba into HK for some time. all works fine and actually my problem is more related to behavior of the IP address of roomba used to connect to the local wifi. 

in the set up i did provide the IP address of the roomba to be able to enable this plugin in homebridge. once a month my wifi router is restarted and when this happens the IP address of roomba does change...  is there a way to make this a permanent ip address?  thank u

**Comment by Chennyisafrag** [comment]
All routers have this feature but the instructions vary. You need to set the roomba to a static/reserved ip address in the router's portal/app.

**Comment by moiko2416** [comment]
Thank u this solved the problem i did set up dhcp address to be stat assigned to roomba
