### ISSUE TITLE
M6 Brava No response in HomeKit. 671 works fine.

### ISSUE THREAD

**Issue by skazzyskills** [karlvr/homebridge-roomba2#40]
My M6 constantly have a 'no response' in HomeKit since launching the plugin. My 671 works fine.

### Expected Behavior
 For there to be a response in HomeKit.

### Current Behavior
 I see the switch for the M6 but 'no response' in HomeKit.

### Steps to Reproduce (for bugs)
 Just installed the plugin. Other Roomba works great. M6 has no response.

### Versions

- **Homebridge**: `homebridge --version`homebridge-config-ui-x v4.41.0
- **Node**:       `node --version`v14.16.0
- **Plugin**:          1.2.0

### Configuration

```json
"accessories": [
        {
            "name": "Ms. Moppy",
            "model": "M6",
            "blid": "xxxx",
            "robotpwd": ":xxxxx",
            "ipaddress": "192.168.7.157",
            "autoRefreshEnabled": true,
            "keepAliveEnabled": true,
            "dockContactSensor": true,
            "runningContactSensor": true,
            "accessory": "Roomba2"
```

### Homebridge Log / Command Output

```

```

**Comment by skazzyskills** [comment]
Just noticed in the Eve app it says battery for my M6 mop is at 0% but Roomba says 100%. I wonder if this is the issue for the constants ‘no response’ I’m getting for this accessory? The plugin is not reading the percentage properly? And therefore it’s giving me a no response? Does anybody have this working?

**Comment by skazzyskills** [comment]
Confirmed. In Homebridge, it registers as 'not charging' and at 0%. BUT, it is actually 100% charged and works if I hit the power button in Homebridge. Hmmm..

**Comment by jdgorelick** [comment]
I'm having the same issue with my m6. Just set it up today and getting No Response

**Comment by zscholz** [comment]
> Confirmed. In Homebridge, it registers as 'not charging' and at 0%. BUT, it is actually 100% charged and works if I hit the power button in Homebridge. Hmmm..

confirmed this behavior also - shows up in the homebridge tiles, and responds to power button presses, but shows in Apple home as “no response” and as said above, the battery reporting function is t correct. 

If there is any troubleshooting I can do - or testing - let me know…

**Comment by pauloruberto** [comment]
+1, seeing the same issue here. s9 works fine, but m6 shows "No Response".

**Comment by karlvr** [comment]
@pauloruberto @zscholz please test with the latest release version and the latest beta and report results.

**Comment by jdgorelick** [comment]
Just updated and tested. Log returns
[22/09/2021, 12:22:38] [Braava Jet m6] Connected to Roomba
[22/09/2021, 12:22:43] [Braava Jet m6] Unable to determine state of Roomba

**Comment by karlvr** [comment]
@jdgorelick thank you. I'm going to close this as a duplicate, and let's proceed with #53
