### ISSUE TITLE
Plugin slowing down Homebridge.

### ISSUE THREAD

**Issue by Honosapiens** [karlvr/homebridge-roomba2#42]
Good morning.

Here is an the specific error that the plugging is giving:

"[homebridge-roomba2] This plugin slows down Homebridge. The read handler for the characteristic 'Charging State' didn't respond at all!. Please check that you properly call the callback! See https://git.io/JtMGR for more info."

How can I fix this?

Thanks!

**Comment by wassimk** [comment]
This is a duplicate of https://github.com/karlvr/homebridge-roomba2/issues/31, which has a solution.

**Comment by karlvr** [comment]
@Honosapiens @wassimk I think this is still an existing issue. I am currently working on it.

**Comment by karlvr** [comment]
@Honosapiens please try out the latest beta version, it has been reengineered to address these issues.
