### ISSUE TITLE
Switch OFF and Roomba start cleaning

### ISSUE THREAD

**Issue by Skyman81** [karlvr/homebridge-roomba2#43]
I using last version of the pluggin.
My Roomba model is: 671.
(only "Enable Keep Alive" is enabled. no other option is set)

Everything is running good BUT every time I ask to SIRI "turn off (or on) all switches" (of my home's lights) all of my light turn off/on and Roomba start cleaning.
Also if Roomba is OFF/ON does not matter... it start cleaning.

(no automation is set)

**Comment by BertoTavira** [comment]
Same here

**Comment by Chennyisafrag** [comment]
Either set a custom scene or a Siri shortcut of everything except the Roomba.

**Comment by Write** [comment]
One workaround i can think off si to change switches to show as 'light' and instead telling Siri 'Turn off all lights'

**Comment by Skyman81** [comment]
> One workaround i can think of si to change switches to show as 'light' instead of switches and instead telling Siri to 'Turn off all lights'

I changed Roomba to show as a "fan"... but I have to test it.

**Comment by Write** [comment]
> 
> 
> > One workaround i can think of si to change switches to show as 'light' instead of switches and instead telling Siri to 'Turn off all lights'
> 
> I changed Roomba to show as a "fan"... but I have to test it.

That may work too actually

**Comment by karlvr** [comment]
@Skyman81 thank you, this is indeed because Roomba is represented as a switch. But also, even though the switch was already off, HomeKit sets it to off again and the plugin puts Roomba into docking mode, when it's already docking...
