### ISSUE TITLE
Room "Zone" Switch

### ISSUE THREAD

**Issue by d2ustin** [karlvr/homebridge-roomba2#44]
Is it possible for those with smart maps to create a switch for a specific zone.  I.E if you press "Kitchen" Roomba will automatically clean the kitchen area?

Thanks so much 

Versions

- **Homebridge**: `homebridge --version` v1.3.4
- **Node**:       `node --version` v14.16.1
- **Plugin**:         v1.2.0

**Comment by i3laze** [comment]
Looks like duplicate to me:
https://github.com/karlvr/homebridge-roomba2/issues/9

**Comment by karlvr** [comment]
Yes, I believe it is a duplicate.
