### ISSUE TITLE
Cannot get iRobot PW

### ISSUE THREAD

**Issue by cloudhoster** [karlvr/homebridge-roomba2#48]
Hi,

First of all thank for the great iRobot plugin for Homebridge.

I installed the plugin successfully and by browsing the plugin directory and entering the command "sudo npm run getrobotpwd 192.168.x.xxx" I got the instructions for configuration including the BLID. But unfortunately I cannot get the password - the following error message occurs: "Error getting password. Follow the instructions and try again.
/homebridge/node_modules/homebridge-roomba2 #".

Do you have any idea what's going wrong?

Thanks & best regards,
C.

**Comment by pauloruberto** [comment]
Are you holding the home button on your robot for 2 seconds before running the script?

**Comment by cloudhoster** [comment]
Hi Roberto,

Yes, I hold the home button for 2 seconds, until there is a few tones. Also the green light on the docking station is on, when I press the home button. There is still no password shown, but I get the BLID.

Any idea what’s going wrong?

Best regards,
C.

**Comment by cloudhoster** [comment]
With new update on iRobot the problem did not occur anymore, so it's solved and I managed to integrate it into HomeKit.
