### ISSUE TITLE
Hello, anyone still taking care of this plugin and responding to reported issus?

### ISSUE THREAD

**Issue by cloudhoster** [karlvr/homebridge-roomba2#54]
### Versions

- **Homebridge**: `homebridge --version`
- **Node**:       `node --version`
- **Plugin**:         

### Configuration

```json

```

### Homebridge Log / Command Output

```

```

**Comment by Althir81** [comment]
seems not... :-(

**Comment by solbadguy2010** [comment]
No, dev is gone. Someone able to fork and take care?

**Comment by karlvr** [comment]
@solbadguy2010 @Althir81 @cloudhoster Not all the time, but some of the time :-)
