### ISSUE TITLE
Transfer back to Homebridge Plugin Group?

### ISSUE THREAD

**Issue by donavanbecker** [karlvr/homebridge-roomba2#55]
@karlvr since you haven’t really worked on this plugin, do you want to transfer this back to the homebridge-plugin Organization?

**Comment by karlvr** [comment]
@donavanbecker Hi, sorry I haven't had any time to commit to it recently. I'm happy to do so. I'm happy to resolve the current PRs and keep an eye out for new ones. Whatever you'd prefer.

**Comment by donavanbecker** [comment]
@karlvr if you think you will continue to give it push updates, then feel free to keep maintaining. If you would rather the homebridge organization have the repo in their name and then you can help maintain it from there till someone else takes It on. We could do that also.

**Comment by karlvr** [comment]
@donavanbecker I'm finally properly on the case. It would seem to make sense for the plugin to live in `homebridge-plugins` though, so I'm happy for it to live in that organisation _and_ to take care of it. Let me know. In the meantime, I'm trying to clear out these issues :-D

**Comment by donavanbecker** [comment]
@karlvr Sounds good. If you transfer it to me. Then I will transfer it to the homebridge-plugin organization

**Comment by karlvr** [comment]
@donavanbecker are you still keen to do this? I'm happy to still contribute to this plugin (going to try to clear the backlog now) but I think it would make more sense in the main org!

**Comment by donavanbecker** [comment]
Sounds good, just transfer npm and GitHub to me, then I will transfer to the organization.
