### ISSUE TITLE
Roomba no reaction

### ISSUE THREAD

**Issue by ands0me** [karlvr/homebridge-roomba2#56]
![8BE4D41D-FD3E-42B6-AC53-612F52072BD0](https://user-images.githubusercontent.com/74508966/130670098-4759d991-059b-4610-a8aa-7c331258a6d8.png)
![0BD02F18-3144-4703-929B-19D4476AD893](https://user-images.githubusercontent.com/74508966/130670102-a97475e8-cb6a-412a-859a-9a38a207236f.png)

OS | Raspbian GNU/Linux Buster (10)
-- | --
raspberrypi
192.168.2.200
Node v15.10.0
NPM v7.21.0
homebridge v1.3.4
/var/homebridge
/var/homebridge/config.json

**Comment by karlvr** [comment]
@ands0me Vielen Dank for ihre issue. Could you please check the IP address of your Roomba again, and make sure that it's still the same IP address that is configured in your accessory?

Has Roomba ever worked with Homebridge for you?

**Comment by ands0me** [comment]
@karlvr Yes it worked properly until a few weeks.
Maybe IRobot changed something in the API?

IP adress is correct.

**Comment by ands0me** [comment]
@karlvr Since the last update it’s working 🎉

**Comment by karlvr** [comment]
@ands0me OK, that's great. I'll close this issue.
