### ISSUE TITLE
getrobotpwd ENOENT: no such file or directory

### ISSUE THREAD

**Issue by joeferrante** [karlvr/homebridge-roomba2#57]
### Current Behavior

running npm run getrobotpwd 192.168.x.x get the following errors 

0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'getrobotpwd',
1 verbose cli   '192.168.20.36'
1 verbose cli ]
2 info using npm@6.14.14
3 info using node@v14.17.5
4 verbose stack Error: ENOENT: no such file or directory, open '/usr/local/lib/package.json'
5 verbose cwd /usr/local/lib/node_modules
6 verbose Linux 5.4.0-81-generic
7 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "getrobotpwd" "192.168.20.36"
8 verbose node v14.17.5
9 verbose npm  v6.14.14
10 error code ENOENT
11 error syscall open
12 error path /usr/local/lib/package.json
13 error errno -2
14 error enoent ENOENT: no such file or directory, open '/usr/local/lib/package.json'
15 error enoent This is related to npm not being able to find a file.
16 verbose exit [ -2, true ]

### Versions

- **Homebridge**: `homebridge --version`
- **Node**:       `node --version`
- **Plugin**:         
# homebridge --version
Initializing HAP-NodeJS v0.9.4...
1.3.4
# node --version
v14.17.5
homebridge-roomba2 v1.2.0
### Configuration

```json

```

### Homebridge Log / Command Output

```

```

**Comment by karlvr** [comment]
@joeferrante thank you, I have actually just updated the README to correct that step in e3f2cfde3b6234efa439f123e7de6f524afb317e
