### ISSUE TITLE
Does it work with roomba 981 or 692

### ISSUE THREAD

**Issue by SergioBraulioCadenaJuarez** [karlvr/homebridge-roomba2#58]
### Versions

- **Homebridge**: `homebridge --version`
- **Node**:       `node --version`
- **Plugin**:         

### Configuration

```json

```

### Homebridge Log / Command Output

```

```

**Comment by vsenn** [comment]
Yes, this plug-in did work with my Roomba 981 for a few month in HomeKit just great but it broke a few days ago with a not accessible error

**Comment by karlvr** [comment]
@vsenn could you please post any log messages? And let's check if your Roomba's IP address has changed please!

**Comment by vsenn** [comment]
>Roomba's IP address has changed 
Hi @karlvr, it works just great. That was a temporary issue with the iRobot's internal IP, not an issue with the plug-in itself, you right. I found it checking the status of Roomba in their official App. Now it's fine. Thank for your support of this plug-in. Let's close it.
