### ISSUE TITLE
Need NPM release for v1.2.1

### ISSUE THREAD

**Issue by rcoletti116** [karlvr/homebridge-roomba2#64]
@karlvr you updated the plugin several months ago, but never pushed an NPM release. Most users will probably still be on v1.2.0. Can you release your v1.2.1?

**Comment by karlvr** [comment]
@rcoletti116 doh, sorry, on it

**Comment by karlvr** [comment]
Resolved df98c74563ac9eb4f676ce12d25b492dceba7fb6
