### ISSUE TITLE
Missing docs on how to modify settings after initial setup

### ISSUE THREAD

**Issue by SpencerKaiser** [karlvr/homebridge-roomba2#65]
### Expected Behavior

After [these changes](https://github.com/karlvr/homebridge-roomba2/commit/e3f2cfde3b6234efa439f123e7de6f524afb317e) to the README, I would like to modify some of my settings but I'm unsure how since many of the keys in the docs are missing from the config JSON and there doesn't seem to be a UI for modifying them.

### Current Behavior

As a user, I'm unsure of how to modify existing settings

### Steps to Reproduce (for bugs)

Setup the plugin and then attempt to make a change to a key from the README such as `autoRefreshEnabled`.

**Comment by rcoletti116** [comment]
Are you using the Homebridge UI or managing your config directly in the config.json file?

**Comment by SpencerKaiser** [comment]
I'm dumb 🤦‍♂️ I ignored the giant `SETTINGS` link in the UI and just went straight to the wrench icon...
