### ISSUE TITLE
Reuse Dorita980 Roomba instances

### ISSUE THREAD

**Issue by karlvr** [karlvr/homebridge-roomba2#66]
If we keep a Dorita980 instance open, the app is apparently not able to communicate with Roomba. It suggests Roomba supports one connection at a time. Therefore we should reuse an existing connection, if possible, when trying to concurrently talk to Roomba.

Implement reference counting.

**Comment by rcoletti116** [comment]
Perhaps semantics, but worth clarifying, the robot can only support one local connection at a time. If Dorita980 is connected the app does falls back to cloud connection.

**Comment by karlvr** [comment]
@rcoletti116 thank you. Right, and we don't have such a fallback mechanism, so I think reusing will be important if we have a situation where we are querying status and starting a clean at the same time.
