### ISSUE TITLE
Feature Request: Battery Percentage as a Separate Tile

### ISSUE THREAD

**Issue by joshuaseltzer** [karlvr/homebridge-roomba2#70]
I would like to start by saying this plugin has been working great for me and has made life a lot more convenient. Thank you for maintaining this plugin!!

I mentioned this new feature in #31: would it be possible to show the battery percentage as a separate tile? I haven't looked into how these plugins are written myself yet, but I use a few other Homebridge plugins that are able to show things like temperature and battery percentage as a separate tile that have no interaction. It's just easier to see at a glance vs. having to view the "settings" for the Roomba tile.

**Comment by karlvr** [comment]
@joshuaseltzer could you link a plugin that shows a battery indicator that you like? I'll duplicate their approach (specifically which service and characteristics they used

**Comment by joshuaseltzer** [comment]
@karlvr the only one I know of that does something similar is the official support with Ecobee, which has a tile for temperature. So honestly I’m not even quite sure if it’s possible.

**Comment by karlvr** [comment]
@joshuaseltzer it seems that the approach is to choose a thing HomeKit knows about, like a temperature sensor or a contact switch, and to repurpose that to show the info you want to show. 

I'm not familiar with what the different types of controls look like, so I'm always interested in what other Homebridge plugins have done to render something similar.

**Comment by karlvr** [comment]
@joshuaseltzer I've experimented a little bit... I haven't been able to work out what sort of thing to add. We currently expose battery level, but of course HomeKit only exposes it if the value is low. I've experimented with exposing the value as a lightbulb with a brightness... but it means HomeKit thinks there's a light, which causes it to display odd stuff and behave weirdly when you ask it to mess with lights. 

So I don't think I can easily progress this. If you can find some screenshots of another HomeKit plugin doing something similar, please post them and reopen this issue.

**Comment by joshuaseltzer** [comment]
@karlvr thanks for looking into it. I guess the more I thought about it, yeah it wouldn't quite make so much sense as a separate tile, especially if HomeKit doesn't already have something like that. I figured maybe we could reuse the "temperature" tiles for something like battery, but that seems like more of a hack than anything.

Thanks again for at least considering it!

**Comment by karlvr** [comment]
@joshuaseltzer yeah, I'm pretty new to the Homebridge world, and it does seem that some plugins do manage to hack together a reuse of different services… I use the Tesla Powerwall plugin and it represents the flow of power as fans! Our own contact sensors are a hack!

If we add a temperature sensor then you're going to see a temperature reported in your room that's going to be weird :-/

I guess we live in hope for more generic reusable types from HomeKit.
