### ISSUE TITLE
"Show docking status as a contact sensor" listed twice in settings (1.3.0-beta.5)

### ISSUE THREAD

**Issue by khad** [karlvr/homebridge-roomba2#72]
### Versions

- **Homebridge**: 1.3.4
- **Node**:  14.17.6
- **Plugin**: 1.3.0-beta.5

<img width="383" alt="Screen Shot 2021-09-22 at 9 22 49 PM" src="https://user-images.githubusercontent.com/758113/134455025-d36e18d4-7f3d-4504-964b-044d27fd701e.png">

I updated from 1.2.2, so it's possible it has something to do with migrating from a previous config.

**Comment by karlvr** [comment]
@khad thank you, it's actually a typo; that first one (the original) is a sensor for the dock (Is Roomba docked?) the second is whether Roomba is actively trying to dock.
