### ISSUE TITLE
Consider restating in the positive: "Do not send home when stopped" -> "Dock when stopped" (1.3.0-beta.5)

### ISSUE THREAD

**Issue by khad** [karlvr/homebridge-roomba2#73]
Settings should be stated in the positive for clarity.

<img width="383" alt="Screen Shot 2021-09-22 at 9 22 49 PM" src="https://user-images.githubusercontent.com/758113/134455631-800a8760-4da5-49d0-bbc7-14d3d3b35efe.png">

### Expected Behavior

The last setting in the screenshot should be:

> ☑️  Dock when stopped

```
"dockOnStop": true,
```
It can default to on/"true".

### Current Behavior

The current setting is a double negative when it is in its default state, which makes it harder to understand at a glance:

> [Do not] "Do not send home when stopped"

Or, in the config:

```
"noDockOnStop": false,
```

### Versions

- **Homebridge**: 1.3.4
- **Node**:  14.17.6
- **Plugin**: 1.3.0-beta.5

**Comment by karlvr** [comment]
@khad thank you, I agree. @rcoletti116 would you like to update, and set a default in the schema and in the code?

**Comment by rcoletti116** [comment]
I'll take a look and think about this one. I had this in the positive before submitting the PR, but there was a reason I changed it.

**Comment by khad** [comment]
Some other possibilities if you want to preserve the current true/false states:

> Pause when turned off

> Pause when switch is off

> Pause when powered off

> Pause when switch is powered off

I don't personally like "powered off", but it's the language Apple uses in the UI.

<img width="142" alt="Screen Shot 2021-09-23 at 8 35 40 AM" src="https://user-images.githubusercontent.com/758113/134538394-4823668c-d421-40fe-b26a-d70e814eb6e6.png">

(I wouldn't recommend "Pause when stopped" because it seems like a logical contradiction. Pause and stop are two different things, no?)

**Comment by rcoletti116** [comment]
I've got a PR coming that should reverse this and make it more logical. As far as pause vs. stop - they are two different things to Roomba, though iRobot's own app has tried to do away with stop. Stop ends a cleaning job and pause does not.

The next version will be "Send home when stopped," with the default being "true" to preserve the current function for all users who update.
