### ISSUE TITLE
Enhancement request: cached status for sensors

### ISSUE THREAD

**Issue by redeemer666** [karlvr/homebridge-roomba2#76]
Hello,

This is an enhancement request for a behavior I have discovered (I’m using the latest beta).

If you create an automation script in Home app that contains an “IF” statement asking for a Roomba sensor status, the automation will fail if the status request ends with an error: this happens often from the test I’ve made, but you can’t see it using the app because, in that case, it will automatically ask for an update if the first fail almost immediately. This is not happening on when running Scripts, it just ask once and then fail the script if report an error.

If you can add a “cached” mode, that will send through homekit the status cached if the call for actual status fails, I think the problem can be “solved”, until Apple itself doesn’t add a “second try” when the automation fail because a device is in error.

**Comment by karlvr** [comment]
@redeemer666 which version of the beta are you on? If you're not on the latest version could you please try upgrading? I believe I have implemented this in #75.

**Comment by redeemer666** [comment]
Hi Karl, you are right I was on Beta 5. Updated to 7 right now, will check as soon as I get home and close this ticket in case :). Thanks a lot for your great work

**Comment by redeemer666** [comment]
Ok with beta 7 the connection is very consistent, and so the automations. Haven't failed once since the installation. Great work!
