### ISSUE TITLE
Roomba 980 not giving password

### ISSUE THREAD

**Issue by cmb991** [karlvr/homebridge-roomba2#80]
All information is displayed when running the getrobotpwd script except the password.  I recently updated to the latest firmware that was available.  

{
  ver: '3',
  hostname: 'Roomba-6977832031633xxx',
  robotname: 'Roomba',
  ip: '192.168.31.x',
  mac: 'F0:03:8C:96:xx:xx',
  sw: 'v2.4.16-126',
  sku: 'R980020',
  nc: 0,
  proto: 'mqtt',
  cap: {
    pose: 1,
    ota: 2,
    multiPass: 2,
    carpetBoost: 1,
    pp: 1,
    binFullDetect: 1,
    langOta: 1,
    maps: 1,
    edge: 1,
    eco: 1,
    svcConf: 1
  },
  blid: '69778320316xxxxx'
}

**Comment by raulphillips** [comment]
Someone around here will have a list of iRobot models supported by this plugin?
