### ISSUE TITLE
Cannot Find blid on i6+ and m6

### ISSUE THREAD

**Issue by wonghc1** [karlvr/homebridge-roomba2#82]
danny@Dannys-MacBook-Pro homebridge-roomba2 % sudo npm run getrobotpwd <MY IP>

> homebridge-roomba2@1.2.2 getrobotpwd /usr/local/lib/node_modules/homebridge-roomba2
> cd node_modules/dorita980 && npm install && node ./bin/getpassword.js "<MY IP>"

npm WARN ajv-keywords@2.1.1 requires a peer of ajv@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-react@6.8.0 requires a peer of eslint@^2.0.0 || ^3.0.0 but none is installed. You must install peer dependencies yourself.

audited 357 packages in 1.486s

5 packages are looking for funding
  run `npm fund` for details

found 9 vulnerabilities (1 low, 5 moderate, 2 high, 1 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
Make sure your robot is on the Home Base and powered on (green lights on). Then press and hold the HOME button (or DOCK+SPOT on some models) on your robot until it plays a series of tones (about 2 seconds). Release the button and your robot will flash WIFI light.
Then press any key here...
Robot Data:
undefined
Password=> :1:5678123098:hf7Ahf89aJlwi01j <= Yes, all this string.
Use this credentials in dorita980 lib :)

**Comment by karlvr** [comment]
@wonghc1 have you been able to resolve this with the latest version?
