### ISSUE TITLE
Get Password Problem

### ISSUE THREAD

**Issue by TomF79** [karlvr/homebridge-roomba2#84]
Hi, I have following Problem:

<img width="820" alt="PNG-Bild" src="https://user-images.githubusercontent.com/93859783/140645813-474038de-15b5-4dda-8b56-e2de659bbe73.png">

What can I do?

BR Tom

**Comment by karlvr** [comment]
@TomF79 I have updated the instructions for this. Please try the latest beta and follow the updates Setup instructions in the README. Please re-open this issue if there are still problems.
