### ISSUE TITLE
Plug-in Slows down homebridge

### ISSUE THREAD

**Issue by CHTHSCH** [karlvr/homebridge-roomba2#87]
Warning message displayed in the home bridge log. Functionality not impaired, but slowed down

### Expected Behavior
No warning message displayed

### Current Behavior
Warning message occurs frequently

### Steps to Reproduce (for bugs)
n/a

### Versions
- **Homebridge**: `1.3.6.`
- **Node**:       `v14.18.1`
- **Plugin**:         v1.2.2

### Configuration
n/a

### Homebridge Log / Command Output
<[13/11/2021, 17:20:59] [homebridge-roomba2] This plugin slows down Homebridge. The read handler for the characteristic 'Battery Level' didn't respond at all!. Please check that you properly call the callback! See https://git.io/JtMGR for more info.
>

**Comment by karlvr** [comment]
Please try the latest beta.

**Comment by Pblondin123** [comment]
> Please try the latest beta.
> […](#)

latest beta looks good.. how to turn off debug mode ? tyia

**Comment by karlvr** [comment]
@astrapowerrr here we're referring to the latest beta of the homebridge-roomba2 plugin, which is 1.3.0 beta 11

**Comment by astrapowerrr** [comment]
when i check that version doesnt exist. only v1.2.2 - latest to select.

and my sensors and switches are visible but only grey and i cant switch them?

so pluging isnt working? maybe on beta?

**Comment by karlvr** [comment]
@astrapowerrr I'm wondering if you're looking in the right place to install the beta plugin. Usually one goes to the plugin page in Homebridge web UI, click the spanner/wrench icon and choose  _Install Previous Version_ then it should appear in that list there. Or if you're not using the UI, you'll find it on npmjs.com.

**Comment by FabianFrank** [comment]
> Please try the latest beta.
> […](#)

I've had the same problem (slow down warnings, Roomba also never updated) with 1.2.2 and it is fixed in 1.3.0-beta.11 for me as well. Thank you!
