### ISSUE TITLE
Whenever Wifi Reconnects iRobot starts a vacuum session

### ISSUE THREAD

**Issue by dhruvb14** [karlvr/homebridge-roomba2#89]
### Expected Behavior
If connection to Homebridge is lost, when reconnected vacuum should not automatically start a vacuum session.

### Current Behavior
If plugin is running in homebridge and wifi reboots then when the plugin reconnects, it starts a vacuum session. This often happens in middle of the night. If I manually reboot my accesspoint while homebridge plugin is running, I can replicate this behavior. If homebridge plugin is disabled and I reboot my accesspoint, it does not start a vacuum session as expected.

### Steps to Reproduce (for bugs)
Listed above

### Versions

- **Homebridge**: `1.3.8`
- **Node**:       `14.18.1`
- **Plugin**:         `v1.3.0-beta.10`

### Configuration

```json
{
            "name": "Roomba",
            "model": "E619820",
            "blid": "31B5C41421917800",
            "robotpwd": "my-correct-password",
            "ipaddress": "192.168.2.20",
            "dockContactSensor": true,
            "runningContactSensor": true,
            "binContactSensor": true,
            "dockingContactSensor": true,
            "homeSwitch": true,
            "stopBehaviour": "pause",
            "_bridge": {
                "username": "0E:5A:E5:42:36:6B",
                "port": 47861
            },
            "accessory": "Roomba2"
        },
```

### Homebridge Log / Command Output

```

```

**Comment by karlvr** [comment]
@dhruvb14 wow that's a strange fault. That's great that you have the beta installed. Could you please show me the log file entries from this plugin when this occurs? The beta has a lot of debug logging, so hopefully we'll see something enlightening!

**Comment by dhruvb14** [comment]
So of course the second I file a bug, I can no longer replicate this. I have force multiple AP reboots and even disabled the roomba's access to internet to see if that was causing this issue. If it happens again I will reopen an issue. I have been monitoring it for last 5 days and it seems to be ok.
