### ISSUE TITLE
Feature Suggestion: Battery as Temperature Sensor

### ISSUE THREAD

**Issue by enoughtobreakthings** [karlvr/homebridge-roomba2#96]
Option to have the Roomba’s battery level display as a temperature sensor. 

### Current Behavior
Battery level can be viewed in a long press of the Roomba’s Homekit tile and scrolling down to the details and settings. 

If the Roomba ON/OFF/PAUSE, HOME tiles and sensors are organized in it’s own Homekit room, the battery level could be displayed as a temperature sensor. 

This would let you check the Roomba’s battery at a glance during a run.

**Comment by karlvr** [comment]
@enoughtobreakthings I think this is possible, but I don't know what the general impression is of misusing sensors. It feels like this will result in odd HomeKit behaviour, so I don't think this is a practical idea unfortunately.
