### ISSUE TITLE
Add ability to disable verbose logging

### ISSUE THREAD

**Issue by adammodlin** [karlvr/homebridge-roomba2#97]
This plugin is spamming my HomeBridge logs, would love for a way to disable it. @karlvr - any objections if I add a config setting to disable verbose logging? If not, I'll submit a PR.

**Comment by adammodlin** [comment]
Looks to be very simple - debug variable is hardcoded to true.

**Comment by adammodlin** [comment]
Added PR #98 .

**Comment by brianleesmith** [comment]
I see the PR but I'm guessing this hasn't been worked into the beta yet?  Really want to use the beta all the time for my j7+, but the logs are basically unusable with debug on all the time.  :(

**Comment by redeemer666** [comment]
Same here, why don’t you add it as a config.json variable instead of hard coding it? I have to use the latest beta since 1.2.2 is not working for my 2 robots but the homebridge log is spammed with debug messages…

**Comment by adammodlin** [comment]
I have a PR (linked above)...but no acknowledgement.

**Comment by karlvr** [comment]
Resolved by #98 thanks @adammodlin
